import { useEffect, useMemo, useState } from 'react';
import { useCompanyDraftTestCases } from '@/hooks/useCompanyDraftTestCases';
import { productApi, segmentApi, testCaseApi } from '@/api/features';
import { Product, Segment, TestCase } from '@/types/features';
import DraftTcCard from './DraftTcCard';
import BulkApplyBar from './BulkApplyBar';

interface CompanyDraftDashboardProps {
  companyId: number;
}

/**
 * Company-level DRAFT TC dashboard.
 *
 * Splits DRAFT TCs into two sections:
 *  🤖 자동 생성 / Path 미배정  — eligible for bulk/single suggestion apply
 *  ✅ 자동 생성 / Path 배정완료 — shows resolved segment path
 *
 * Only DRAFT TCs with `testStudioJobId` are shown (i.e. the ones generated by Test Studio).
 * Path application happens ONLY on explicit user action — no forced/automatic injection.
 */
export default function CompanyDraftDashboard({ companyId }: CompanyDraftDashboardProps) {
  const { testCases, isLoading, error, refresh } = useCompanyDraftTestCases(companyId);
  const [products, setProducts] = useState<Product[]>([]);
  const [segmentsByProduct, setSegmentsByProduct] = useState<Record<number, Segment[]>>({});
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  const [busyTcIds, setBusyTcIds] = useState<Set<number>>(new Set());
  const [bulkBusy, setBulkBusy] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  // Load products (for name display) and their segments (for path label)
  useEffect(() => {
    const load = async () => {
      try {
        const ps = await productApi.getByCompanyId(companyId);
        setProducts(ps);
        const segEntries = await Promise.all(
          ps.map(async (p) => [p.id, await segmentApi.getByProductId(p.id)] as const)
        );
        const map: Record<number, Segment[]> = {};
        segEntries.forEach(([pid, segs]) => {
          map[pid] = segs;
        });
        setSegmentsByProduct(map);
      } catch (e) {
        console.error('Failed to load products/segments', e);
      }
    };
    load();
  }, [companyId]);

  const productNameById = useMemo(() => {
    const map: Record<number, string> = {};
    products.forEach((p) => {
      map[p.id] = p.name;
    });
    return map;
  }, [products]);

  // Build (productId, segmentId) → segment name map and also resolve full path labels.
  const resolvePathLabel = (tc: TestCase): string => {
    if (!tc.path || tc.path.length === 0) return '';
    const segs = segmentsByProduct[tc.productId] ?? [];
    const byId = new Map<number, Segment>();
    segs.forEach((s) => byId.set(s.id, s));
    return tc.path
      .map((id) => byId.get(id)?.name ?? `#${id}`)
      .join(' > ');
  };

  // Partition: 미배정 (path empty) vs 배정완료 (path non-empty) — Test Studio jobs only.
  const testStudioDrafts = testCases.filter((tc) => tc.testStudioJobId != null);
  const unassigned = testStudioDrafts.filter((tc) => !tc.path || tc.path.length === 0);
  const assigned = testStudioDrafts.filter((tc) => tc.path && tc.path.length > 0);

  // Only drafts that have a stored suggestion are eligible for bulk "apply suggestion"
  const bulkEligible = unassigned.filter(
    (tc) => tc.suggestedSegmentPath && tc.suggestedSegmentPath.length > 0
  );

  const selectedEligible = bulkEligible.filter((tc) => selectedIds.has(tc.id));
  const allEligibleSelected =
    bulkEligible.length > 0 && selectedEligible.length === bulkEligible.length;

  const handleToggleSelect = (id: number, next: boolean) => {
    setSelectedIds((prev) => {
      const s = new Set(prev);
      if (next) s.add(id);
      else s.delete(id);
      return s;
    });
  };

  const handleSelectAll = (next: boolean) => {
    if (next) {
      setSelectedIds(new Set(bulkEligible.map((tc) => tc.id)));
    } else {
      setSelectedIds(new Set());
    }
  };

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  };

  const handleApplySuggestion = async (tcId: number) => {
    setBusyTcIds((prev) => new Set(prev).add(tcId));
    try {
      const result = await testCaseApi.applySuggestedPath(tcId);
      if (result.resolvedLength === 0) {
        showToast(
          result.error === 'NO_SUGGESTION'
            ? 'Claude 추천 경로가 없어 적용할 수 없습니다. 수동 지정을 사용하세요.'
            : '추천 경로를 Segment 트리에서 찾지 못했습니다. 수동 지정이 필요합니다.'
        );
      } else if (!result.fullMatch) {
        showToast(
          `일부만 매칭되었습니다 (${result.resolvedLength}/${result.suggestedLength}). 가장 깊은 유효 레벨에 배치했습니다.`
        );
      } else {
        showToast('추천을 적용했습니다.');
      }
      await refresh();
    } catch (e) {
      console.error('apply-suggested-path failed', e);
      showToast('추천 적용에 실패했습니다.');
    } finally {
      setBusyTcIds((prev) => {
        const s = new Set(prev);
        s.delete(tcId);
        return s;
      });
    }
  };

  const handleBulkApply = async () => {
    const ids = selectedEligible.map((tc) => tc.id);
    if (ids.length === 0) return;
    setBulkBusy(true);
    try {
      const results = await testCaseApi.bulkApplySuggestedPath(ids);
      const applied = results.filter((r) => r.resolvedLength > 0).length;
      const full = results.filter((r) => r.fullMatch).length;
      showToast(`${applied}/${ids.length}건 적용 (완전 매칭 ${full}건).`);
      setSelectedIds(new Set());
      await refresh();
    } catch (e) {
      console.error('bulk apply failed', e);
      showToast('일괄 적용에 실패했습니다.');
    } finally {
      setBulkBusy(false);
    }
  };

  const handleManualAssign = (_tcId: number) => {
    // TODO (Step 7): open Segment Tree Picker modal
    showToast('수동 Path 지정 UI는 Step 7에서 연결됩니다.');
  };

  if (isLoading) {
    return <div className="p-6 text-sm text-gray-500">DRAFT 목록을 불러오는 중…</div>;
  }
  if (error) {
    return <div className="p-6 text-sm text-red-600">{error}</div>;
  }

  return (
    <div className="space-y-6">
      {toast && (
        <div className="rounded-md bg-indigo-50 border border-indigo-200 px-4 py-2 text-sm text-indigo-700">
          {toast}
        </div>
      )}

      {/* 미배정 섹션 */}
      <section data-testid="unassigned-section">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-lg font-semibold text-gray-900">
            🤖 자동 생성 / Path 미배정 ({unassigned.length})
          </h2>
        </div>

        {bulkEligible.length > 0 && (
          <div className="mb-3">
            <BulkApplyBar
              selectedCount={selectedEligible.length}
              totalEligible={bulkEligible.length}
              onSelectAll={handleSelectAll}
              onApplyAll={handleBulkApply}
              busy={bulkBusy}
              allSelected={allEligibleSelected}
            />
          </div>
        )}

        {unassigned.length === 0 ? (
          <div className="rounded-md border border-dashed border-gray-200 bg-white p-6 text-center text-sm text-gray-500">
            Path 미배정 DRAFT TC가 없습니다.
          </div>
        ) : (
          <div className="space-y-2">
            {unassigned.map((tc) => (
              <DraftTcCard
                key={tc.id}
                testCase={tc}
                productName={productNameById[tc.productId]}
                isSelected={selectedIds.has(tc.id)}
                onToggleSelect={
                  tc.suggestedSegmentPath && tc.suggestedSegmentPath.length > 0
                    ? handleToggleSelect
                    : undefined
                }
                onApplySuggestion={handleApplySuggestion}
                onManualAssign={handleManualAssign}
                showCheckbox={
                  !!tc.suggestedSegmentPath && tc.suggestedSegmentPath.length > 0
                }
                showSuggestion
                busy={busyTcIds.has(tc.id) || bulkBusy}
              />
            ))}
          </div>
        )}
      </section>

      {/* 배정완료 섹션 */}
      <section data-testid="assigned-section">
        <h2 className="text-lg font-semibold text-gray-900 mb-3">
          ✅ 자동 생성 / Path 배정완료 ({assigned.length})
        </h2>
        {assigned.length === 0 ? (
          <div className="rounded-md border border-dashed border-gray-200 bg-white p-6 text-center text-sm text-gray-500">
            Path가 배정된 DRAFT TC가 아직 없습니다.
          </div>
        ) : (
          <div className="space-y-2">
            {assigned.map((tc) => (
              <DraftTcCard
                key={tc.id}
                testCase={tc}
                productName={productNameById[tc.productId]}
                segmentPathLabel={resolvePathLabel(tc)}
                onManualAssign={handleManualAssign}
                busy={busyTcIds.has(tc.id)}
              />
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
